language:
 - c

compiler:
  - gcc

sudo: false
addons:
  apt:
    update: true
    packages:
    - build-essential
    - fxload
    - gnupg
    - libftdi-dev
    - libreadline-dev
    - libusb-1.0-0-dev
    - python-yaml
    - realpath
    - util-linux

git:
  submodules: false

env:
  global:
   - HDMI2USB_UDEV_IGNORE=1
   - CLEAN_CHECK=1
   - PREBUILT_DIR="/tmp/HDMI2USB-firmware-prebuilt"
   # Travis reports incorrect the hosts number of processors, override to 2
   # cores.
   - JOBS=2

install:
 - export CPUS="$C" && echo "CPUS='$CPUS'"
 - export PLATFORMS="$P" && echo "PLATFORMS='$PLATFORMS'"
 - export TARGETS="$T" && echo "TARGETS='$TARGETS'"
 - export FIRMWARE="$F" && echo "FIRMWARE='$FIRMWARE'"
 - $PWD/.travis/setup.sh

script:
 - $PWD/.travis/build.sh

after_success:
 - $PWD/.travis/update-prebuilt-list.sh

notifications:
 email:
  - hdmi2usb-spam@googlegroups.com
 irc:
  channels:
   - "chat.freenode.net#hdmi2usb"
  template:
   - "[%{repository_slug}/%{branch}#%{build_number}] (%{commit}): %{message} (%{build_url})"

jobs:
  fail_fast: true
  include:
  - stage: Targets
    env: C=lm32 P=opsis T="hdmi2usb"
